### ISSUE TITLE
cmake issue

### ISSUE THREAD

**Issue by sainisanjay** [MikeS96/3d_obj_detection#1]
I am getting below issue could you please help me to relsove?

```
CMake Error at CMakeLists.txt:9 (add_executable):
  add_executable cannot create target "pcl_features" because an imported
  target with the same name already exists.


CMake Error at CMakeLists.txt:10 (target_link_libraries):
  IMPORTED library can only be used with the INTERFACE keyword of
  target_link_libraries


-- Configuring incomplete, errors occurred!
See also "/home/saini/data/3d_obj_detection/build/CMakeFiles/CMakeOutput.log".
```

**Comment by MikeS96** [comment]
Hi @sainisanjay,

This error is unfamiliar to me. However, I will suggest the procedure that I follow to make it run (I just tested and everything went fine)

- Install PCL - `sudo apt install libpcl-dev`
- Create the build folder, if you have created it before delete it and create a new one - `mkdir build`
- Compile... `cmake..`
- `make`
- Use the binaries within build folder - `./pcl_features`

I am using cmake version 3.10.2 and gcc version 7.5.0. Hope this information is useful.

**Comment by vikkikid** [comment]
> I am getting below issue could you please help me to relsove?
> 
> ```
> CMake Error at CMakeLists.txt:9 (add_executable):
>   add_executable cannot create target "pcl_features" because an imported
>   target with the same name already exists.
> 
> 
> CMake Error at CMakeLists.txt:10 (target_link_libraries):
>   IMPORTED library can only be used with the INTERFACE keyword of
>   target_link_libraries
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/saini/data/3d_obj_detection/build/CMakeFiles/CMakeOutput.log".
> ```

How did you actually solve the problem? I have the same one
